services:
    postgres:
        container_name: postgres
        image: postgres:18.1-alpine3.23
        restart: always
        env_file: ".env"
        volumes:
            - /data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    solid:
        container_name: solid
        build: .
        image: solid
        volumes:
            - type: bind
              source: .
              target: /app
        ports:
            - 3000:3000
        env_file: ".env"
        depends_on:
            - postgres